version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth-service
    ports:
      - 5000:5000
    environment:
      - DATABASE_URI=mongodb://mongo:27017/mydb
      - JWT_SECRET=MmPMVOkr
    volumes:
      - .:/app
    depends_on:
      - mongo
    links:
      - mongo
